version: "3.8"

services:
  app:
    image: dsaboard-app
    build:
      context: ./app/
      target: PROD
    ports:
      - 8000:80

  server:
    image: dsaboard-server
    build:
      context: ./server/
      target: PROD
    ports:
      - 80:80
